# Generated by Django 3.0.9 on 2023-09-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20230925_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ('serial', '-created'), 'verbose_name': 'Робот', 'verbose_name_plural': 'Роботы'},
        ),
    ]
