# Generated by Django 3.0.9 on 2023-09-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230925_1706'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('customer',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(max_length=5, verbose_name='Серийный номер робота'),
        ),
    ]
